version: "3"
services:

  getquote:
    image: getquote
    build:
      context: ./parent
    ports:
      - "8080:8080"
    command: sh -c "java -jar gs-spring-boot-docker-0.1.0.jar --service.location=http://quoter:8080/quote"

  quoter:
    image: quoter
    build: ./child
    ports:
      - "8090:8080"
    command: sh -c "java -jar gs-spring-boot-docker-0.1.0.jar"
