version: "3"
services:

  getquote:
    image: getquote
    build: parent
    ports:
      - "8080:8080"
    command: sh -c "java -cp app:app/lib/* hello.Application --service.location=quoter:8090"

  quoter:
    image: quoter
    build: child
    ports:
      - "8090:8080"
    command: sh -c "java -cp app:app/lib/* hello.Application"
